version: "3.3"
services:
  accounting_of_orders:
    container_name: accounting_of_orders
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DBNAME=postgres
      - POSTGRES_PASSWORD=admin
      - HOST=10.0.2.47
      - PORT=5432
      - TZ=Asia/Novosibirsk
    ports:
      - 8004:8004